services:
  - type: web
    name: flet-app
    runtime: python
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.10"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"